imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    transport: gmail
    #delivery_address:  vecinos200@gmail.com
    #encryption: ssl
    #host:      smtp.gmail.com
    #auth_mode: login
    username: vecinos200@gmail.com
    password: vecinos200
    #disable_delivery: true


monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true
