IncidenciaBundle:
    resource: "@IncidenciaBundle/Resources/config/routing.yml"
    prefix:   /

MensajeBundle:
    resource: "@MensajeBundle/Resources/config/routing.yml"
    prefix:   /

ReservaBundle:
    resource: "@ReservaBundle/Resources/config/routing.yml"
    prefix:   /
    
EspacioBundle:
    resource: "@EspacioBundle/Resources/config/routing.yml"
    prefix:   /

JuntaBundle:
    resource: "@JuntaBundle/Resources/config/routing.yml"
    prefix:   /

InmuebleBundle:
    resource: "@InmuebleBundle/Resources/config/routing.yml"
    prefix:   /

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

DropboxBundle:
    #resource: "/opt/lampp/htdocs/Vecinos2.0/src/Symplex/DropboxBundle/Resources/config/routing.yml"
    resource: "@SymplexDropboxBundle/Resources/config/routing.yml"
    prefix:   /

# import routes from a controller directory
#dropbox:
#    resource: "@DropboxBundle/Controller"
#    type:     annotation

sonata:
   resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
   prefix: /admin

_sonata_admin:
   resource: .
   type: sonata_admin
   prefix: /admin

# Rutas de las páginas estáticas del sitio
estatica:
    pattern:  /sitio/{pagina}
    defaults: { _controller: EspacioBundle:Sitio:estatica }
   
# Ruta para mostrar el formulario de contacto
contacto:
    pattern:  /contacto
    defaults: { _controller: EspacioBundle:Sitio:contacto }

portada:
   pattern: /
   defaults: { _controller: EspacioBundle:Default:portada }



# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
