security:

#    acl:
#        connection: default
    
    firewalls:
        # Firewall de la parte de administración o backend
        backend:
            pattern:        ^/admin
            provider:       administradores
            http_basic:     ~
        # Firewall global utilizado en la parte pública o frontend
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                default_target_path: /usuario/
                always_use_default_target_path: true
                login_path: usuario_login
                check_path: usuario_login_check
            logout:
                path:       usuario_logout
            remember_me:
                key:        vecinos1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
    
    access_control:
        - { path: ^/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/admin/*,         roles: ROLE_ADMIN }
    
    encoders:
        Vecinos\UsuarioBundle\Entity\Usuario:        plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    
    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: Vecinos\UsuarioBundle\Entity\Usuario, property: email }
        # Usuarios del backend
        administradores:
            users:
                # user = admin, pass = 1234
                admin: { password: 1234, roles: ROLE_ADMIN }
                #admin: { password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_ADMIN }
    
#    role_hierarchy:
#        ROLE_ADMIN: [ROLE_USUARIO, ROLE_ALLOWED_TO_SWITCH]

# security:
#     encoders:
#         Symfony\Component\Security\Core\User\User: plaintext
# 
#     role_hierarchy:
#         ROLE_ADMIN:       ROLE_USER
#         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
# 
#     providers:
#         in_memory:
#             users:
#                 user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                 admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
# 
#     firewalls:
#         dev:
#             pattern:  ^/(_(profiler|wdt)|css|images|js)/
#             security: false
# 
#         login:
#             pattern:  ^/demo/secured/login$
#             security: false
# 
#         secured_area:
#             pattern:    ^/demo/secured/
#             form_login:
#                 check_path: /demo/secured/login_check
#                 login_path: /demo/secured/login
#             logout:
#                 path:   /demo/secured/logout
#                 target: /demo/
#             #anonymous: ~
#             #http_basic:
#             #    realm: "Secured Demo Area"
# 
#     access_control:
#         #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#         #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
