parameters:
#    usuario.example.class: Vecinos\UsuarioBundle\Example

services:
   sonata.vecinos.admin.reserva:
       class: Vecinos\ReservaBundle\Admin\ReservaAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: 'Reservas de la comunidad', label: Reservas }
       arguments:
           - null
           - Vecinos\ReservaBundle\Entity\Reserva
           - ReservaBundle:Admin