parameters:
#    incidencia.example.class: Vecinos\IncidenciaBundle\Example

services:
   sonata.vecinos.admin.incidencia:
       class: Vecinos\IncidenciaBundle\Admin\IncidenciaAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: 'Incidencias de la comunidad', label: Incidencias }
       arguments:
           - null
           - Vecinos\IncidenciaBundle\Entity\Incidencia
           - IncidenciaBundle:Admin