parameters:
#    inmueble.example.class: Vecinos\InmuebleBundle\Example

services:
#    inmueble.example:
#        class: %inmueble.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
