parameters:
#    inmueble.example.class: Vecinos\InmuebleBundle\Example

services:
   sonata.vecinos.admin.inmueble:
       class: Vecinos\InmuebleBundle\Admin\InmuebleAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: 'Inmuebles de la comunidad', label: Inmuebles }
       arguments:
           - null
           - Vecinos\InmuebleBundle\Entity\Inmueble
           - InmuebleBundle:Admin