# Ruta para que los nuevos usuarios puedan registrarse en el sitio
usuario_registro:
    pattern:  /registro
    defaults: { _controller: UsuarioBundle:Default:registro }

# Ruta para mostrar el perfil del usuario logueado
usuario_perfil:
    pattern:  /perfil
    defaults: { _controller: UsuarioBundle:Default:perfil }

# Ruta para mostrar el perfil del usuario que cre贸 la incidencia
usuario_perfil_incidencia:
    pattern:  /perfil/{id}
    defaults: { _controller: UsuarioBundle:Default:perfilIncidencia }
    requirements:
        _method:  GET
        id: \d+

# Ruta para ver todas las reservas del usuario logueado
usuario_reservas:
    pattern:  /reservas
    defaults: { _controller: UsuarioBundle:Default:reservas }

# Ruta para ver todas las incidencias del usuario logueado
usuario_incidencias:
    pattern:  /incidencias
    defaults: { _controller: UsuarioBundle:Default:incidencias}

usuario_incidencias_tags:
    pattern:  /incidencias/filtro/{tag}
    defaults: { _controller: UsuarioBundle:Default:tags}

# Ruta para ver una incidencia concreta
usuario_incidencias_id:
    pattern:  /incidencias/{id}
    defaults: { _controller: UsuarioBundle:Default:mostrar }
    requirements:
        _method:  GET
        id: \d+

usuario_incidencia_nueva:
    pattern:  /incidencias/nueva
    defaults: { _controller: IncidenciaBundle:Default:incidenciaNueva}

# Ruta a la aplicacion
usuario_aplicacion:
    pattern:  /
    defaults: { _controller: UsuarioBundle:Default:aplicacion }

# Ruta para ver todas las juntas del usuario logueado
usuario_juntas:
    pattern:  /juntas.{_format}
    defaults: { _controller: UsuarioBundle:Default:juntas, _format: html }
    requirements:
        _format: html|rss

# Ruta para crear una nueva junta
usuario_junta_nueva:
    pattern:  /juntas/nueva
    defaults: { _controller: JuntaBundle:Default:juntaNueva }

# Ruta para crear eliminar la nueva junta
usuario_junta_nueva_si:
    pattern:  /juntas/nueva/si
    defaults: { _controller: UsuarioBundle:Default:juntaSi }

# Ruta para confirmar la junta
usuario_junta_nueva_confirmacion:
    pattern:  /juntas/nueva/confirmacion
    defaults: { _controller: UsuarioBundle:Default:confirmacion }

# Ruta para la acci贸n de login de de los usuarios del frontend
usuario_login:
    pattern:   /login
    defaults:  { _controller: UsuarioBundle:Default:login }

# Ruta para la acci贸n que comprueba el login del frontend
usuario_login_check:
    pattern:   /login_check

# Ruta para la acci贸n de logout de los usuarios del frontend extranet
usuario_logout:
    pattern:   /logout