parameters:
#    junta.example.class: Vecinos\JuntaBundle\Example

services:
   sonata.vecinos.admin.junta:
       class: Vecinos\JuntaBundle\Admin\JuntaAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: 'Juntas de la comunidad', label: Juntas }
       arguments:
           - null
           - Vecinos\JuntaBundle\Entity\Junta
           - JuntaBundle:Admin