parameters:
#    usuario.example.class: Vecinos\UsuarioBundle\Example

services:
   sonata.vecinos.admin.mensaje:
       class: Vecinos\MensajeBundle\Admin\MensajeAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: 'Mensajes de la comunidad', label: Mensajes }
       arguments:
           - null
           - Vecinos\MensajeBundle\Entity\Mensaje
           - MensajeBundle:Admin