parameters:
#    espacio.example.class: Vecinos\EspacioBundle\Example

services:
   sonata.vecinos.admin.espacio:
       class: Vecinos\EspacioBundle\Admin\EspacioAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: 'Espacios de alquiler', label: Espacios }
       arguments:
           - null
           - Vecinos\EspacioBundle\Entity\Espacio
           - EspacioBundle:Admin