parameters:
#    espacio.example.class: Vecinos\EspacioBundle\Example

services:
#    espacio.example:
#        class: %espacio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
